[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"


#Remappings for OpenZeppelin
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]


# Optimizer settings
optimizer = true
optimizer_runs = 200

# Testing
fuzz_runs = 256
fuzz_max_test_rejects = 50000

# Verbosity
verbosity = 1

# Test options
[fuzz]
runs = 256
max_test_rejects = 50000

[fmt]
line_length = 120
number_of_lines_per_file = 80

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[doc]
include = []


[profile.default.coverage]
reporters = ["lcov", "text"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
